# Site settings
title: Notes
email: tom@shen.io
description: > # this means to ignore newlines until "baseurl:"
  Notes on classes at CMU.
baseurl: "/notes" # the subpath of your site, e.g. /blog/
url: "http://www.tomshen.me" # the base hostname & protocol for your site
twitter_username: tomshen
github_username:  tomshen
permalink: /:categories/:year/:month/:day/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
